backend:
  name: github
  branch: main
  repo: worthfollow/worthfollow

publish_mode: editorial_workflow
media_folder: src/public/media
public_folder: /media
collections:
  - name: repos
    label: Repos
    folder: src/data/repos
    extension: yml
    format: yaml
    editor:
      preview: false
    create: true
    fields:
      - label: label
        name: label
        widget: string
      - label: order
        name: order
        widget: number
        required: false
      - label: repos
        name: repos
        widget: list
        fields:
          - { label: name, name: name, widget: string }
          - { label: category, name: category, widget: string, required: false }